# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Users/orahmoun/.brew/Cellar/cmake/3.25.0/bin/cmake

# The command to remove a file.
RM = /Users/orahmoun/.brew/Cellar/cmake/3.25.0/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/orahmoun/Webserv

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/orahmoun/Webserv

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Users/orahmoun/.brew/Cellar/cmake/3.25.0/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Users/orahmoun/.brew/Cellar/cmake/3.25.0/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/orahmoun/Webserv/CMakeFiles /Users/orahmoun/Webserv//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/orahmoun/Webserv/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Webserver

# Build rule for target.
Webserver: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Webserver
.PHONY : Webserver

# fast build rule for target.
Webserver/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Webserver.dir/build.make CMakeFiles/Webserver.dir/build
.PHONY : Webserver/fast

Request.o: Request.cpp.o
.PHONY : Request.o

# target to build an object file
Request.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Webserver.dir/build.make CMakeFiles/Webserver.dir/Request.cpp.o
.PHONY : Request.cpp.o

Request.i: Request.cpp.i
.PHONY : Request.i

# target to preprocess a source file
Request.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Webserver.dir/build.make CMakeFiles/Webserver.dir/Request.cpp.i
.PHONY : Request.cpp.i

Request.s: Request.cpp.s
.PHONY : Request.s

# target to generate assembly for a file
Request.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Webserver.dir/build.make CMakeFiles/Webserver.dir/Request.cpp.s
.PHONY : Request.cpp.s

Response.o: Response.cpp.o
.PHONY : Response.o

# target to build an object file
Response.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Webserver.dir/build.make CMakeFiles/Webserver.dir/Response.cpp.o
.PHONY : Response.cpp.o

Response.i: Response.cpp.i
.PHONY : Response.i

# target to preprocess a source file
Response.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Webserver.dir/build.make CMakeFiles/Webserver.dir/Response.cpp.i
.PHONY : Response.cpp.i

Response.s: Response.cpp.s
.PHONY : Response.s

# target to generate assembly for a file
Response.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Webserver.dir/build.make CMakeFiles/Webserver.dir/Response.cpp.s
.PHONY : Response.cpp.s

Route.o: Route.cpp.o
.PHONY : Route.o

# target to build an object file
Route.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Webserver.dir/build.make CMakeFiles/Webserver.dir/Route.cpp.o
.PHONY : Route.cpp.o

Route.i: Route.cpp.i
.PHONY : Route.i

# target to preprocess a source file
Route.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Webserver.dir/build.make CMakeFiles/Webserver.dir/Route.cpp.i
.PHONY : Route.cpp.i

Route.s: Route.cpp.s
.PHONY : Route.s

# target to generate assembly for a file
Route.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Webserver.dir/build.make CMakeFiles/Webserver.dir/Route.cpp.s
.PHONY : Route.cpp.s

RouterBuilder.o: RouterBuilder.cpp.o
.PHONY : RouterBuilder.o

# target to build an object file
RouterBuilder.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Webserver.dir/build.make CMakeFiles/Webserver.dir/RouterBuilder.cpp.o
.PHONY : RouterBuilder.cpp.o

RouterBuilder.i: RouterBuilder.cpp.i
.PHONY : RouterBuilder.i

# target to preprocess a source file
RouterBuilder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Webserver.dir/build.make CMakeFiles/Webserver.dir/RouterBuilder.cpp.i
.PHONY : RouterBuilder.cpp.i

RouterBuilder.s: RouterBuilder.cpp.s
.PHONY : RouterBuilder.s

# target to generate assembly for a file
RouterBuilder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Webserver.dir/build.make CMakeFiles/Webserver.dir/RouterBuilder.cpp.s
.PHONY : RouterBuilder.cpp.s

Server.o: Server.cpp.o
.PHONY : Server.o

# target to build an object file
Server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Webserver.dir/build.make CMakeFiles/Webserver.dir/Server.cpp.o
.PHONY : Server.cpp.o

Server.i: Server.cpp.i
.PHONY : Server.i

# target to preprocess a source file
Server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Webserver.dir/build.make CMakeFiles/Webserver.dir/Server.cpp.i
.PHONY : Server.cpp.i

Server.s: Server.cpp.s
.PHONY : Server.s

# target to generate assembly for a file
Server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Webserver.dir/build.make CMakeFiles/Webserver.dir/Server.cpp.s
.PHONY : Server.cpp.s

ServerBuilder.o: ServerBuilder.cpp.o
.PHONY : ServerBuilder.o

# target to build an object file
ServerBuilder.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Webserver.dir/build.make CMakeFiles/Webserver.dir/ServerBuilder.cpp.o
.PHONY : ServerBuilder.cpp.o

ServerBuilder.i: ServerBuilder.cpp.i
.PHONY : ServerBuilder.i

# target to preprocess a source file
ServerBuilder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Webserver.dir/build.make CMakeFiles/Webserver.dir/ServerBuilder.cpp.i
.PHONY : ServerBuilder.cpp.i

ServerBuilder.s: ServerBuilder.cpp.s
.PHONY : ServerBuilder.s

# target to generate assembly for a file
ServerBuilder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Webserver.dir/build.make CMakeFiles/Webserver.dir/ServerBuilder.cpp.s
.PHONY : ServerBuilder.cpp.s

ServerPoll.o: ServerPoll.cpp.o
.PHONY : ServerPoll.o

# target to build an object file
ServerPoll.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Webserver.dir/build.make CMakeFiles/Webserver.dir/ServerPoll.cpp.o
.PHONY : ServerPoll.cpp.o

ServerPoll.i: ServerPoll.cpp.i
.PHONY : ServerPoll.i

# target to preprocess a source file
ServerPoll.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Webserver.dir/build.make CMakeFiles/Webserver.dir/ServerPoll.cpp.i
.PHONY : ServerPoll.cpp.i

ServerPoll.s: ServerPoll.cpp.s
.PHONY : ServerPoll.s

# target to generate assembly for a file
ServerPoll.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Webserver.dir/build.make CMakeFiles/Webserver.dir/ServerPoll.cpp.s
.PHONY : ServerPoll.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Webserver.dir/build.make CMakeFiles/Webserver.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Webserver.dir/build.make CMakeFiles/Webserver.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Webserver.dir/build.make CMakeFiles/Webserver.dir/main.cpp.s
.PHONY : main.cpp.s

parsing/location.o: parsing/location.cpp.o
.PHONY : parsing/location.o

# target to build an object file
parsing/location.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Webserver.dir/build.make CMakeFiles/Webserver.dir/parsing/location.cpp.o
.PHONY : parsing/location.cpp.o

parsing/location.i: parsing/location.cpp.i
.PHONY : parsing/location.i

# target to preprocess a source file
parsing/location.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Webserver.dir/build.make CMakeFiles/Webserver.dir/parsing/location.cpp.i
.PHONY : parsing/location.cpp.i

parsing/location.s: parsing/location.cpp.s
.PHONY : parsing/location.s

# target to generate assembly for a file
parsing/location.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Webserver.dir/build.make CMakeFiles/Webserver.dir/parsing/location.cpp.s
.PHONY : parsing/location.cpp.s

parsing/parser.o: parsing/parser.cpp.o
.PHONY : parsing/parser.o

# target to build an object file
parsing/parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Webserver.dir/build.make CMakeFiles/Webserver.dir/parsing/parser.cpp.o
.PHONY : parsing/parser.cpp.o

parsing/parser.i: parsing/parser.cpp.i
.PHONY : parsing/parser.i

# target to preprocess a source file
parsing/parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Webserver.dir/build.make CMakeFiles/Webserver.dir/parsing/parser.cpp.i
.PHONY : parsing/parser.cpp.i

parsing/parser.s: parsing/parser.cpp.s
.PHONY : parsing/parser.s

# target to generate assembly for a file
parsing/parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Webserver.dir/build.make CMakeFiles/Webserver.dir/parsing/parser.cpp.s
.PHONY : parsing/parser.cpp.s

parsing/server.o: parsing/server.cpp.o
.PHONY : parsing/server.o

# target to build an object file
parsing/server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Webserver.dir/build.make CMakeFiles/Webserver.dir/parsing/server.cpp.o
.PHONY : parsing/server.cpp.o

parsing/server.i: parsing/server.cpp.i
.PHONY : parsing/server.i

# target to preprocess a source file
parsing/server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Webserver.dir/build.make CMakeFiles/Webserver.dir/parsing/server.cpp.i
.PHONY : parsing/server.cpp.i

parsing/server.s: parsing/server.cpp.s
.PHONY : parsing/server.s

# target to generate assembly for a file
parsing/server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Webserver.dir/build.make CMakeFiles/Webserver.dir/parsing/server.cpp.s
.PHONY : parsing/server.cpp.s

parsing/tokengen.o: parsing/tokengen.cpp.o
.PHONY : parsing/tokengen.o

# target to build an object file
parsing/tokengen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Webserver.dir/build.make CMakeFiles/Webserver.dir/parsing/tokengen.cpp.o
.PHONY : parsing/tokengen.cpp.o

parsing/tokengen.i: parsing/tokengen.cpp.i
.PHONY : parsing/tokengen.i

# target to preprocess a source file
parsing/tokengen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Webserver.dir/build.make CMakeFiles/Webserver.dir/parsing/tokengen.cpp.i
.PHONY : parsing/tokengen.cpp.i

parsing/tokengen.s: parsing/tokengen.cpp.s
.PHONY : parsing/tokengen.s

# target to generate assembly for a file
parsing/tokengen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Webserver.dir/build.make CMakeFiles/Webserver.dir/parsing/tokengen.cpp.s
.PHONY : parsing/tokengen.cpp.s

tools.o: tools.cpp.o
.PHONY : tools.o

# target to build an object file
tools.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Webserver.dir/build.make CMakeFiles/Webserver.dir/tools.cpp.o
.PHONY : tools.cpp.o

tools.i: tools.cpp.i
.PHONY : tools.i

# target to preprocess a source file
tools.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Webserver.dir/build.make CMakeFiles/Webserver.dir/tools.cpp.i
.PHONY : tools.cpp.i

tools.s: tools.cpp.s
.PHONY : tools.s

# target to generate assembly for a file
tools.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Webserver.dir/build.make CMakeFiles/Webserver.dir/tools.cpp.s
.PHONY : tools.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Webserver"
	@echo "... Request.o"
	@echo "... Request.i"
	@echo "... Request.s"
	@echo "... Response.o"
	@echo "... Response.i"
	@echo "... Response.s"
	@echo "... Route.o"
	@echo "... Route.i"
	@echo "... Route.s"
	@echo "... RouterBuilder.o"
	@echo "... RouterBuilder.i"
	@echo "... RouterBuilder.s"
	@echo "... Server.o"
	@echo "... Server.i"
	@echo "... Server.s"
	@echo "... ServerBuilder.o"
	@echo "... ServerBuilder.i"
	@echo "... ServerBuilder.s"
	@echo "... ServerPoll.o"
	@echo "... ServerPoll.i"
	@echo "... ServerPoll.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... parsing/location.o"
	@echo "... parsing/location.i"
	@echo "... parsing/location.s"
	@echo "... parsing/parser.o"
	@echo "... parsing/parser.i"
	@echo "... parsing/parser.s"
	@echo "... parsing/server.o"
	@echo "... parsing/server.i"
	@echo "... parsing/server.s"
	@echo "... parsing/tokengen.o"
	@echo "... parsing/tokengen.i"
	@echo "... parsing/tokengen.s"
	@echo "... tools.o"
	@echo "... tools.i"
	@echo "... tools.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

