# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Users/orahmoun/.brew/Cellar/cmake/3.25.0/bin/cmake

# The command to remove a file.
RM = /Users/orahmoun/.brew/Cellar/cmake/3.25.0/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/orahmoun/Webserv

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/orahmoun/Webserv

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Users/orahmoun/.brew/Cellar/cmake/3.25.0/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Users/orahmoun/.brew/Cellar/cmake/3.25.0/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/orahmoun/Webserv/CMakeFiles /Users/orahmoun/Webserv//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/orahmoun/Webserv/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Webserv

# Build rule for target.
Webserv: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Webserv
.PHONY : Webserv

# fast build rule for target.
Webserv/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Webserv.dir/build.make CMakeFiles/Webserv.dir/build
.PHONY : Webserv/fast

Request.o: Request.cpp.o
.PHONY : Request.o

# target to build an object file
Request.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Webserv.dir/build.make CMakeFiles/Webserv.dir/Request.cpp.o
.PHONY : Request.cpp.o

Request.i: Request.cpp.i
.PHONY : Request.i

# target to preprocess a source file
Request.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Webserv.dir/build.make CMakeFiles/Webserv.dir/Request.cpp.i
.PHONY : Request.cpp.i

Request.s: Request.cpp.s
.PHONY : Request.s

# target to generate assembly for a file
Request.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Webserv.dir/build.make CMakeFiles/Webserv.dir/Request.cpp.s
.PHONY : Request.cpp.s

Route.o: Route.cpp.o
.PHONY : Route.o

# target to build an object file
Route.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Webserv.dir/build.make CMakeFiles/Webserv.dir/Route.cpp.o
.PHONY : Route.cpp.o

Route.i: Route.cpp.i
.PHONY : Route.i

# target to preprocess a source file
Route.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Webserv.dir/build.make CMakeFiles/Webserv.dir/Route.cpp.i
.PHONY : Route.cpp.i

Route.s: Route.cpp.s
.PHONY : Route.s

# target to generate assembly for a file
Route.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Webserv.dir/build.make CMakeFiles/Webserv.dir/Route.cpp.s
.PHONY : Route.cpp.s

RouterBuilder.o: RouterBuilder.cpp.o
.PHONY : RouterBuilder.o

# target to build an object file
RouterBuilder.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Webserv.dir/build.make CMakeFiles/Webserv.dir/RouterBuilder.cpp.o
.PHONY : RouterBuilder.cpp.o

RouterBuilder.i: RouterBuilder.cpp.i
.PHONY : RouterBuilder.i

# target to preprocess a source file
RouterBuilder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Webserv.dir/build.make CMakeFiles/Webserv.dir/RouterBuilder.cpp.i
.PHONY : RouterBuilder.cpp.i

RouterBuilder.s: RouterBuilder.cpp.s
.PHONY : RouterBuilder.s

# target to generate assembly for a file
RouterBuilder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Webserv.dir/build.make CMakeFiles/Webserv.dir/RouterBuilder.cpp.s
.PHONY : RouterBuilder.cpp.s

Server.o: Server.cpp.o
.PHONY : Server.o

# target to build an object file
Server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Webserv.dir/build.make CMakeFiles/Webserv.dir/Server.cpp.o
.PHONY : Server.cpp.o

Server.i: Server.cpp.i
.PHONY : Server.i

# target to preprocess a source file
Server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Webserv.dir/build.make CMakeFiles/Webserv.dir/Server.cpp.i
.PHONY : Server.cpp.i

Server.s: Server.cpp.s
.PHONY : Server.s

# target to generate assembly for a file
Server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Webserv.dir/build.make CMakeFiles/Webserv.dir/Server.cpp.s
.PHONY : Server.cpp.s

ServerBuilder.o: ServerBuilder.cpp.o
.PHONY : ServerBuilder.o

# target to build an object file
ServerBuilder.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Webserv.dir/build.make CMakeFiles/Webserv.dir/ServerBuilder.cpp.o
.PHONY : ServerBuilder.cpp.o

ServerBuilder.i: ServerBuilder.cpp.i
.PHONY : ServerBuilder.i

# target to preprocess a source file
ServerBuilder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Webserv.dir/build.make CMakeFiles/Webserv.dir/ServerBuilder.cpp.i
.PHONY : ServerBuilder.cpp.i

ServerBuilder.s: ServerBuilder.cpp.s
.PHONY : ServerBuilder.s

# target to generate assembly for a file
ServerBuilder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Webserv.dir/build.make CMakeFiles/Webserv.dir/ServerBuilder.cpp.s
.PHONY : ServerBuilder.cpp.s

ServerPoll.o: ServerPoll.cpp.o
.PHONY : ServerPoll.o

# target to build an object file
ServerPoll.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Webserv.dir/build.make CMakeFiles/Webserv.dir/ServerPoll.cpp.o
.PHONY : ServerPoll.cpp.o

ServerPoll.i: ServerPoll.cpp.i
.PHONY : ServerPoll.i

# target to preprocess a source file
ServerPoll.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Webserv.dir/build.make CMakeFiles/Webserv.dir/ServerPoll.cpp.i
.PHONY : ServerPoll.cpp.i

ServerPoll.s: ServerPoll.cpp.s
.PHONY : ServerPoll.s

# target to generate assembly for a file
ServerPoll.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Webserv.dir/build.make CMakeFiles/Webserv.dir/ServerPoll.cpp.s
.PHONY : ServerPoll.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Webserv.dir/build.make CMakeFiles/Webserv.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Webserv.dir/build.make CMakeFiles/Webserv.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Webserv.dir/build.make CMakeFiles/Webserv.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Webserv"
	@echo "... Request.o"
	@echo "... Request.i"
	@echo "... Request.s"
	@echo "... Route.o"
	@echo "... Route.i"
	@echo "... Route.s"
	@echo "... RouterBuilder.o"
	@echo "... RouterBuilder.i"
	@echo "... RouterBuilder.s"
	@echo "... Server.o"
	@echo "... Server.i"
	@echo "... Server.s"
	@echo "... ServerBuilder.o"
	@echo "... ServerBuilder.i"
	@echo "... ServerBuilder.s"
	@echo "... ServerPoll.o"
	@echo "... ServerPoll.i"
	@echo "... ServerPoll.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

